### ISSUE TITLE
istio-pilot may skip event handlers when deployed with the Charmed Kubeflow bundle

### ISSUE THREAD

**Issue by DnPlas** [canonical/istio-operators#113]
#### Behaviour

When deployed in a large bundle with multiple charms related to it (like the [Charmed Kubeflow bundle](https://github.com/canonical/bundle-kubeflow/blob/main/releases/1.6/beta/kubeflow/bundle.yaml)), istio-pilot may skip the method that sends `gateway-info` to remote units and/or the handler for the default gateway, which causes the following:

1) If the [`handle_default_gateway`](https://github.com/canonical/istio-operators/blob/main/charms/istio-pilot/src/charm.py#L111) is not called, the `default-gateway` never gets created.
2) If the [`handle_gateway_info_relation`](https://github.com/canonical/istio-operators/blob/main/charms/istio-pilot/src/charm.py#L162) is not called, related remove units will never get the gateway info, which prevents them to complete their start up.

Note that even though this is wrong behaviour, istio-pilot will not fail.

#### Workarounds

For 1): `juju run --unit istio-pilot/0 -- "export JUJU_DISPATCH_PATH=hooks/config-changed; ./dispatch"`

For 2) This behaviour should be corrected by [this change](https://github.com/canonical/istio-operators/pull/111)

**Comment by agathanatasha** [comment]
Related [juju bug](https://bugs.launchpad.net/juju/+bug/1983669)

**Comment by i-chvets** [comment]
This issue is still seen. Need to address it in Istio Event Handling epic.

**Comment by ca-scribner** [comment]
Closed by #261
