### ISSUE TITLE
Istio-pilot does not work with istio-ingressgateway with kind egress

### ISSUE THREAD

**Issue by Barteus** [canonical/istio-operators#128]
The istio-pilot requires the name of the service created by istio-ingressgateway to be exactly **istio-ingressgateway-workload**. This value is hardcoded.
https://github.com/canonical/istio-operators/blob/8d54b30a1a1d7ac6a4918d13beda4d320ccdd881/charms/istio-pilot/src/charm.py#L327

Istio-ingressgateway can create the gateway workload service with different names based on the "kind" config.
- istio-ingressgateway
- istio-egressgateway
https://github.com/canonical/istio-operators/blob/2a4cc67ae59878775bf13595df62b63cab8f5796/charms/istio-gateway/src/manifest.yaml#L301

If you want to deploy Istio in the cluster with Ingress Controller you need to set the kind to egress and create a proper ingress rule for it.

The result is:
```
istio-ingressgateway/0*       active    idle   100.120.187.129                     
istio-pilot/0*                waiting   idle   100.120.187.142                     Missing istio-ingressgateway-workload service, deferring this event
```

Reproduce:
```
juju deploy istio-pilot --channel=1.11/stable --trust --config default-gateway=kubeflow-gateway
juju deploy istio-gateway istio-ingressgateway --channel=1.11/stable --trust --config kind=egress
juju relate istio-pilot:istio-pilot istio-ingressgateway:istio-pilot
```

**Comment by DomFleischmann** [comment]
We are not expecting to support this functionality, but your specific usecase will be covered with #130
