### ISSUE TITLE
Add option to use a `NodePort` `service` for the istio gateway

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-operators#175]
Currently we support deploying either a `LoadBalancer` or `ClusterIP` `service` to access the Kubeflow dashboard.  This was implemented in #129.  We should extend this support to also enable `NodePort` access.

A possible solution to this would be to implement essentially the same thing as in #129 but for `NodePort`.  However, as `NodePort`s have different properties from the currently supported types, our way of [checking for an available gateway](https://github.com/canonical/istio-operators/blob/699264547be0e8ab90901024620cec6a37455d8a/charms/istio-pilot/src/charm.py#L356) in istio-pilot will fail with a `NodePort` (because `NodePort` services do not get IP addresses).  This will necessitate changes to istio-pilot to handle this as well.

**Comment by beliaev-maksim** [comment]
@ca-scribner 
so, will this lib work in this case?

https://charmhub.io/observability-libs/libraries/kubernetes_service_patch
