### ISSUE TITLE
Istio-pilot is error state after upgrade 1.6 to 1.7 which prevents dashboard access.

### ISSUE THREAD

**Issue by i-chvets** [canonical/istio-operators#182]
Istio-pilot is error state which prevents dashboard access.

[Jira1](https://warthogs.atlassian.net/browse/KF-1101)
[Jira2](https://warthogs.atlassian.net/browse/KF-1107)

**Comment by DnPlas** [comment]
Thanks for raising this @i-chvets, but I was not able to reproduce the issue. Could you provide some logs and steps to reproduce so we can try again?

**Comment by i-chvets** [comment]
Works. Verified in latest upgrade.
