### ISSUE TITLE
istio-pilot charm requires internet access to upgrade from v1.11 to 1.12

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-operators#265]
istio-pilot v1.12+ uses `istioctl` to upgrade the istio daemon service.  Version 1.12 of `istioctl` requires internet connectivity (specifically to github) to do this upgrade (see more background in [this thread](https://github.com/istio/istio/issues/28995#issuecomment-772323915)).  This causes a problem for secured deployments (behind a strict proxy, offline, etc), preventing istio-pilot from being upgraded.

As a workaround, to upgrade from v1.11 to 1.12 users can remove the istio-pilot v1.11 application and then deploy a new istio-pilot v1.12.  This will result in v1.12 of istiod being deployed, but will also remove the Istio CRDs in the process (which could lose user data, say if they use VirtualServices for their own applications).

**Comment by ca-scribner** [comment]
Closed as `wontfix` because it applies only to v1.12, and because users can work around this by removing and redeploying the application.  If there's a really compelling need, we might be able to work around this by reconfiguring the upgrade command and vendoring the needed files, but it doesn't appear worth the effort.

**Comment by NohaIhab** [comment]
reopening this to provide a workaround
was able to reproduce the issue by these steps:
 - `juju deploy istio-pilot --trust --channel=1.11/stable`
 - `juju download istio-pilot --channel=1.12/stable`
 - disconnect from the internet to simulate an airgapped environment
 - `juju refresh istio-pilot --path=./<local-charm-path>`

**result**: istio-pilot stuck in error state
 
istio-pilot charm container logs:
```
[container-agent] 2023-05-23 14:19:17 WARNING upgrade-charm 2023-05-23T14:19:17.579481Z	info	Error: failed to generate Istio configs from file [] for the current version: 1.11.0, error: Get "https://github.com/istio/istio/releases/download/1.11.0/istio-1.11.0-linux-amd64.tar.gz": dial tcp 140.82.114.4:443: i/o timeout
[container-agent] 2023-05-23 14:19:17 WARNING upgrade-charm 
[container-agent] 2023-05-23 14:19:17 WARNING upgrade-charm Error: failed to generate Istio configs from file [] for the current version: 1.11.0, error: Get "https://github.com/istio/istio/releases/download/1.11.0/istio-1.11.0-linux-amd64.tar.gz": dial tcp 140.82.114.4:443: i/o timeout
```
