### ISSUE TITLE
[ingressgateway] HTTPS access not working

### ISSUE THREAD

**Issue by phvalguima** [canonical/istio-operators#32]
Hi,

I am deploying kubeflow on:
Charmed Kubernetes: 1.19
Kubeflow: deployed as ```juju deploy cs:kubeflow```

After deployed, I've updated the kubeflow-gateway on gateways.networking.istio.io as described on [istio docs](https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-tls-ingress-gateway-for-a-single-host).

And created a secret as follows:
```
$ cat secret.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: istio-ingressgw-tls-secert
  namespace: istio-ingressgateway
type: kubernetes.io/tls
data:
  tls.crt: <REDACTED>
  tls.key: <REDACTED>
```

The first issue I've faced is the missing istio-ingressgateway, as described on ingress logs: https://pastebin.ubuntu.com/p/tB6HVWNgNp/

After creating the namespace and re-adding the secrets to that namespace instead, I can see Istio picks up the certificate but then crashes: https://pastebin.ubuntu.com/p/dMm3FXsnQ8/

Following the error code, I can find this discussion on Istio forum: https://discuss.istio.io/t/istio-multicluster-custom-ca-issues/5974/10
Which mentions that Istio 1.5.0 has this issue but not Istio 1.5.1.

Indeed, I can get access to istio and confirm that istio-ingressgateway is running on 1.5.0:
```
root@istio-ingressgateway-55ddc68cd5-bltjz:/# /usr/local/bin/pilot-agent version
version.BuildInfo{Version:"1.5.0", GitRevision:"c3c353285578eb68b334fc8766746b754b6b3789", GolangVersion:"go1.13.8", BuildStatus:"Clean", GitTag:"1.5.0"}
```

There are two changes needed:
1) Upgrade istio image to 1.5.1
2) Find an option that allows to define the namespace for Istio data and set it as the same namespace as the Istio itself

**Comment by phvalguima** [comment]
@knkski it then fails with:
```
$ kubectl logs -n kubeflow istio-ingressgateway-687dd76467-ssrxb
2021-10-07T09:14:13.888162Z	error	unknown command "proxy" for "pilot-discovery"
Error: unknown command "proxy" for "pilot-discovery"
Run 'pilot-discovery --help' for usage.
```

**Comment by ca-scribner** [comment]
Sorry @phvalguima we lost track of this.  Did you ever resolve it yourself?  We made a lot of modifications in the most recent release (KF 1.4) but Istio is still the same - not sure if it would have resolved this.  We will be updating istio in the next release as well (KF 1.4, ~March).

I'm going to close this issue for now as stale, but if you're still hitting it please reopen
