### ISSUE TITLE
Publish documentation with information about the Istio CNI plugin enablement and overview

### ISSUE THREAD

**Issue by DnPlas** [canonical/istio-operators#368]
### Context

Users need a public document they can reference for enabling the Istio CNI plugin. 

### What needs to get done

Document the highlights of the Istio CNI plugin and how to enable it in the `istio-pilot` charm.

### Definition of Done

1. A blog post in discourse
2. A section in the charmed-kubeflow.io/docs with this same information

**Comment by orfeas-k** [comment]
This has been completed https://charmed-kubeflow.io/docs/enable-istio-cni-plugin
