### ISSUE TITLE
Spec out the Istio HA configuration

### ISSUE THREAD

**Issue by DnPlas** [canonical/istio-operators#468]
### Context

This is the first step of having HA support in our Istio. This is inspired by https://github.com/canonical/istio-operators/issues/399  

We want to make the gateway provided by the istio-gateway Charm more resilient, particularly to the loss of a Node, by enabling:

* The ingress Deployment to have more than one replica
* The Pods of the ingress Deployment to automatically be scheduled on different nodes

### What needs to get done

1. A spec that defines the above, including the changes that have to be done in the `istio-operators` and the upgrade path.
2. Define which versions of Istio will be affected (currently in use are 1.17-1.22)

### Definition of Done

A spec that defines Istio HA.

**Comment by NohaIhab** [comment]
specced out and approved in spec `KF103`
