### ISSUE TITLE
Update any guides that set istio-pilot config `default-gateway` to use new `default-gateways` config

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-operators#51]
#31 updated the `default-gateway` config option to handle a comma separated list of gateways, with the config option being renamed `default-gateways` to reflect this.  This option is called out in some kubeflow/other guides and needs to be updated.

This is also a breaking change in some of our CI, but that will at least not be a silent issue.

**Comment by DnPlas** [comment]
This does not apply anymore as the config has been renamed to `default-gateway`.
