### ISSUE TITLE
istio-gateway can go to `Active` without being active (status handling problems)

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-operators#70]
`istio-gateway` still has status handling issues, setting `Active` in the charm `__init__` when some (but not all required) prereqs are available.  This means when the unbound `update_status` event fires, the charm goes to `Active` regardless of whether it is actually working.  To demonstrate, deploy the charm without an istio-pilot relation, `juju model-config update-status-hook-interval=10s`, and wait

**Comment by DomFleischmann** [comment]
Status handling for istio-gateway has now been addressed and should not give false positives anymore.
