### ISSUE TITLE
No gateway created in latest/edge

### ISSUE THREAD

**Issue by natalian98** [canonical/istio-operators#94]
When deploying istio bundle from `latest/edge` channel (revisions 79 and 58), the charms get active but no gateway is created.

Steps to reproduce:
`juju deploy istio-gateway istio-ingressgateway --channel latest/edge --config kind=ingress --trust`
`juju deploy istio-pilot --channel latest/edge --config default-gateway=kubeflow-gateway --trust`
`juju relate istio-pilot:istio-pilot istio-ingressgateway:istio-pilot`

`kubectl get gateway -A` # no gateway was created

This results in a problem with accessing the dashboard if deployed in a bundle.

The workaround is to ~~deploy older revisions or~~ create the gateway manually:
~~`juju deploy istio-gateway istio-ingressgateway --revision 54 --channel latest/edge --config kind=ingress --trust`~~
~~`juju deploy istio-pilot --revision 75 --channel latest/edge --config default-gateway=kubeflow-gateway --trust`~~

```
$ kubectl get gateway kubeflow-gateway -n kubeflow -o yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  creationTimestamp: "2022-06-21T10:15:25Z"
  generation: 1
  labels:
    app.istio-pilot.io/is-workload-entity: "true"
    app.juju.is/created-by: istio-pilot
  name: kubeflow-gateway
  namespace: kubeflow
  resourceVersion: "1620"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/kubeflow/gateways/kubeflow-gateway
  uid: bd6fd16e-3fee-4856-8fd8-e2d2575cd610
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

**Comment by DnPlas** [comment]
Hi @natalian98 , I tried reproducing this issue, unfortunately without success. These were my strategies:

##### Deploying only istio operators
```
juju deploy istio-gateway istio-ingressgateway --channel latest/edge --config kind=ingress --trust
juju deploy istio-pilot --channel latest/edge --config default-gateway=kubeflow-gateway --trust
juju relate istio-pilot:istio-pilot istio-ingressgateway:istio-pilot
```
Output: I get the gateway

##### Deploying kubeflow bundle with istio operators pointing at `latest/edge`
[This](https://raw.githubusercontent.com/canonical/bundle-kubeflow/master/bundle-kubeflow.yaml) exact same bundle, but with the following changes for istio

```yaml
  istio-ingressgateway:  { charm: istio-gateway, channel: latest/edge, scale: 1, trust: true, options: { kind: "ingress" } }
  istio-pilot:           { charm: istio-pilot, channel: latest/edge, scale: 1, trust: true, options: { default-gateway: "kubeflow-gateway" } }
```

Output: I get the gateway

#### My setup
Microk8s 1.21/stable rbac enabled
Juju latest/stable
istio-pilot rev 79
istio-gateway rev 58

@natalian98 do you mind sharing your config and what you are deploying when this issue happens? If you provide the bundle that's failing, that's also useful.

**Comment by natalian98** [comment]
Hi @DnPlas, thanks for looking into this.
**The bundle:**
```
bundle: kubernetes
name: kubeflow
applications:
  dex-auth:
    charm: "/home/ubuntu/dex-auth-operator/dex-auth_ubuntu-20.04-amd64.charm"
    resources:
      dex-auth-image: "dexidp/dex:v2.31.2"
    scale: 1
    trust: true
  istio-ingressgateway:          { charm: istio-gateway,           channel: latest/edge, scale: 1, options: { kind: "ingress" }, trust: true}
  istio-pilot:                   { charm: istio-pilot,             channel: latest/edge, scale: 1, options: { default-gateway: "kubeflow-gateway" }, trust: true }
  kubeflow-dashboard:            { charm: kubeflow-dashboard,      channel: latest/edge, scale: 1 }
  kubeflow-profiles:             { charm: kubeflow-profiles,       channel: latest/edge, scale: 1 }
  oidc-gatekeeper:               { charm: oidc-gatekeeper,         channel: latest/stable, scale: 1 }
relations:
- [dex-auth:oidc-client, oidc-gatekeeper:oidc-client]
- [istio-pilot:ingress, dex-auth:ingress]
- [istio-pilot:ingress, kubeflow-dashboard:ingress]
- [istio-pilot:ingress, oidc-gatekeeper:ingress]
- [istio-pilot:ingress-auth, oidc-gatekeeper:ingress-auth]
- [istio-pilot:istio-pilot, istio-ingressgateway:istio-pilot]
- [kubeflow-profiles, kubeflow-dashboard]
```
**My setup:**
microk8s 1.21/stable dns storage ingress metallb:10.64.140.43-10.64.140.49 enabled

**Comment by natalian98** [comment]
Hi @DnPlas, I wasn't really clear with the steps to reproduce, sorry for that. I wrongly assumed it would give the same result if not deployed in a bundle but it may make a difference.
So here are the exact steps:
1. Install `microk8s 1.21/stable` and enable `dns storage rbac ingress metallb:10.64.140.43-10.64.140.49`
I also deployed without enabling rbac - same final result.
2. Deploy the following bundle:
```
bundle: kubernetes
name: kubeflow
applications:
  dex-auth:
    charm: "/home/ubuntu/dex-auth-operator/dex-auth_ubuntu-20.04-amd64.charm"
    resources:
      dex-auth-image: "dexidp/dex:v2.31.2"
    scale: 1
    trust: true
  istio-ingressgateway:          { charm: istio-gateway,           channel: latest/edge, scale: 1, options: { kind: "ingress" }, trust: true}
  istio-pilot:                   { charm: istio-pilot,             channel: latest/edge, scale: 1, options: { default-gateway: "kubeflow-gateway" }, trust: true }
  kubeflow-dashboard:            { charm: kubeflow-dashboard,      channel: latest/edge, scale: 1 }
  kubeflow-profiles:             { charm: kubeflow-profiles,       channel: latest/edge, scale: 1 }
  oidc-gatekeeper:               { charm: oidc-gatekeeper,         channel: latest/stable, scale: 1 }
relations:
- [dex-auth:oidc-client, oidc-gatekeeper:oidc-client]
- [istio-pilot:ingress, dex-auth:ingress]
- [istio-pilot:ingress, kubeflow-dashboard:ingress]
- [istio-pilot:ingress, oidc-gatekeeper:ingress]
- [istio-pilot:ingress-auth, oidc-gatekeeper:ingress-auth]
- [istio-pilot:istio-pilot, istio-ingressgateway:istio-pilot]
- [kubeflow-profiles, kubeflow-dashboard]
```
(the dex charm is from this [PR](https://github.com/canonical/dex-auth-operator/pull/62))
3. Add juju config:
```
juju config dex-auth public-url=http://10.64.140.43.nip.io/
juju config oidc-gatekeeper public-url=http://10.64.140.43.nip.io/
juju config dex-auth static-username=admin
juju config dex-auth static-password=admin
```
4. Once the model gets active, check if all k8s resources are ready:
```
$ kubectl get all -n kubeflow
NAME                                                READY   STATUS    RESTARTS   AGE
pod/modeloperator-556b464b56-tjkgd                  1/1     Running   0          4m9s
pod/kubeflow-dashboard-operator-0                   1/1     Running   0          113s
pod/kubeflow-profiles-operator-0                    1/1     Running   0          104s
pod/istiod-588f95c45f-g5gqr                         1/1     Running   0          108s
pod/dex-auth-0                                      2/2     Running   0          2m29s
pod/oidc-gatekeeper-operator-0                      1/1     Running   0          99s
pod/istio-ingressgateway-0                          1/1     Running   0          2m19s
pod/istio-pilot-0                                   1/1     Running   0          2m3s
pod/istio-ingressgateway-workload-89ff56576-lk7tv   1/1     Running   0          66s
pod/kubeflow-dashboard-95d46dbc7-fxkk5              1/1     Running   0          72s
pod/kubeflow-profiles-6846dc856f-jvf68              2/2     Running   0          80s
pod/oidc-gatekeeper-67c4ccc746-c66rb                1/1     Running   0          63s

NAME                                     TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                                 AGE
service/modeloperator                    ClusterIP      10.152.183.148   <none>         17071/TCP                               4m9s
service/dex-auth-endpoints               ClusterIP      None             <none>         <none>                                  2m31s
service/istio-ingressgateway             ClusterIP      10.152.183.204   <none>         65535/TCP                               2m21s
service/istio-ingressgateway-endpoints   ClusterIP      None             <none>         <none>                                  2m21s
service/istio-pilot                      ClusterIP      10.152.183.107   <none>         65535/TCP                               2m10s
service/istio-pilot-endpoints            ClusterIP      None             <none>         <none>                                  2m9s
service/dex-auth                         ClusterIP      10.152.183.129   <none>         5556/TCP                                2m31s
service/kubeflow-dashboard-operator      ClusterIP      10.152.183.138   <none>         30666/TCP                               117s
service/istiod                           ClusterIP      10.152.183.205   <none>         15010/TCP,15012/TCP,443/TCP,15014/TCP   108s
service/kubeflow-profiles-operator       ClusterIP      10.152.183.58    <none>         30666/TCP                               107s
service/oidc-gatekeeper-operator         ClusterIP      10.152.183.109   <none>         30666/TCP                               100s
service/kubeflow-profiles                ClusterIP      10.152.183.32    <none>         8080/TCP,8081/TCP                       80s
service/kubeflow-dashboard               ClusterIP      10.152.183.149   <none>         8082/TCP                                72s
service/istio-ingressgateway-workload    LoadBalancer   10.152.183.54    10.64.140.43   80:31953/TCP,443:32094/TCP              65s
service/oidc-gatekeeper                  ClusterIP      10.152.183.11    <none>         8080/TCP                                63s

NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/modeloperator                   1/1     1            1           4m9s
deployment.apps/istiod                          1/1     1            1           108s
deployment.apps/istio-ingressgateway-workload   1/1     1            1           66s
deployment.apps/kubeflow-dashboard              1/1     1            1           72s
deployment.apps/kubeflow-profiles               1/1     1            1           80s
deployment.apps/oidc-gatekeeper                 1/1     1            1           63s

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/modeloperator-556b464b56                  1         1         1       4m9s
replicaset.apps/istiod-588f95c45f                         1         1         1       108s
replicaset.apps/istio-ingressgateway-workload-89ff56576   1         1         1       66s
replicaset.apps/kubeflow-dashboard-95d46dbc7              1         1         1       72s
replicaset.apps/kubeflow-profiles-6846dc856f              1         1         1       80s
replicaset.apps/oidc-gatekeeper-67c4ccc746                1         1         1       63s

NAME                                           READY   AGE
statefulset.apps/kubeflow-dashboard-operator   1/1     114s
statefulset.apps/kubeflow-profiles-operator    1/1     104s
statefulset.apps/dex-auth                      1/1     2m29s
statefulset.apps/oidc-gatekeeper-operator      1/1     99s
statefulset.apps/istio-ingressgateway          1/1     2m19s
statefulset.apps/istio-pilot                   1/1     2m3s
```
Check if the gateway was created:
```
NAME                                         REFERENCE           TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istiod   Deployment/istiod   <unknown>/80%   1         5         1          108s
$ kubectl get gateway -A
No resources found
```

**Comment by ca-scribner** [comment]
@natalian98 in the above bundle, is 
`dex-auth-image: "dexidp/dex:v2.31.2"`
supposed to be
`oci-image: "dexidp/dex:v2.31.2"`
?

I am getting errors saying `unrecognized resource "dex-auth-image"`

**Comment by ca-scribner** [comment]
I am unable to reproduce this.  I have tried using the [above bundle](https://github.com/canonical/istio-operators/issues/94#issuecomment-1164657340) and steps, but a gateway is created as desired.

I saw you had `microk8s enable ingress` as part of your setup, which by default I do not use.  But I tried deploying with and without that enabled, and both times a gateway was created successfully.  

What environment are you testing on, local or maybe AWS?  Perhaps that has an effect.  Also, do you have any `juju debug-log`s for istio-pilot when this happens?  I wonder if we can determine what happened from those.  afaict if the gateway doesn't get created, it would probably fail spectacularly.  Also, if you have a setup that did not get a gateway, I'd be curious what happened if you changed the `default-gateway` config value.  That should again trigger an attempt to create a gateway, which either may succeed or may fail the same as the first time.

**Comment by natalian98** [comment]
This is possibly environment-specific. The gateway gets created [in CI](https://github.com/canonical/dex-auth-operator/runs/7216548508?check_suite_focus=true#step:6:8).

**Comment by ca-scribner** [comment]
I believe [by design](https://juju.is/docs/sdk/events#heading--config-changed) `config-changed` will occur immediately before start, but not sure why that doesn't result in a working gateway...

To debug this, it might be helpful to add detailed logging in the gateway creation hooks (print value of each variable along the way, etc) to see what is actually happening.  I'm not sure from reading the code why it would get through an config-changed event without making the gateway...

**Comment by natalian98** [comment]
I find it difficult to state what is causing this issue, so I collected my thoughts on possible causes:

**Environment**
We suspected it's because of deploying on AWS, but it is unlikely that this issue is bound to environment only as:
1) Standard gh runners are not aws-hosted and same issue can be observed in CI
2) sometimes the gateway gets created (see [this CI run](https://github.com/canonical/dex-auth-operator/runs/7216548508?check_suite_focus=true#step:6:8)), while it wasn't the case for [another run](https://github.com/canonical/dex-auth-operator/runs/7252180413?check_suite_focus=true#step:6:7)

**Lack of permissions that block creation / lightkube bug**
1) If that was caused by any missing permission on AWS/k8s that blocked gateway creation, it wouldn't be possible to create it manually or 'force' the creation by charm by emitting another config-changed
2) Similarly, if that was a bug in lightkube, the gateway wouldn't get created after re-setting the default-gateway name with `juju config`

**Deploying in integration test** (pylib-juju logic)
1) Unlikely to be the case (see the above CI run)
2) Observed also when deploying a bundle

**Deploying in a bundle / other charms events interfering istio**
1) I opened a [PR](https://github.com/canonical/istio-operators/pull/97) adding a test for gateway creation to see if gets created when no other charms than istio are deployed, I'm now waiting for the integration to finish.
2) I deployed the same bundle as in reproduce steps but built locally latest fixes from [this PR](https://github.com/canonical/istio-operators/pull/96) and the gateway got created, which excludes bundle to be the cause.
[Here](https://pastebin.canonical.com/p/7bmyYKkTBj/) are more detailed logs from same bundle deployments, with the difference that:
 - the one with istio built locally created a gateway
 - the one with istio latest/edge didn't create a gateway
This PR fixes some resource handler errors and refactors lightkube usage. I don't see a direct relation with the gateway issue but once it's merged I will re-run the impacted CI tests, since it seems to work very well on AWS.

**Comment by DnPlas** [comment]
Hi @natalian98 , after several attempts I was able to reproduce the issue. Here's my setup:

* Ubuntu 20.04.4 LTS
* juju              2.9.32         19681  2.9/stable        canonical✓    classic
* microk8s          v1.21.13       3410   1.21/stable       canonical✓    classic
* charmcraft        2.0.0          1033   latest/candidate  canonical✓    classic
* microk8s enable: storage, rbac, metallb, istio (?) ha-cluster, dns

I did a couple of comparisons like deploying istio alone, deploying in a bundle, etc. What I found is that if you use the bundle you posted above and remove the relation between istio and dex, it magically works. At the moment I am not sure why this relation in particular gets in the way of the event handler for `configChanged`, which in the case of istio-pilot is `handle_default_gateway` (the one that creates gateways) but I will investigate further.

Workaround for canonical/dex-auth-operator#62: if you are deploying this in an integration test, I recommend you deploy istio-pilot and istio-ingressgateway first and wait for them to be idle, similar to what we do [here](https://github.com/canonical/knative-operators/blob/main/tests/test_bundle.py#L70) and then deploy dex, and only after that you relate dex to istio-pilot. I think this workaround is better than "forcing" the gateway creation and is a bit more scalable.

**Comment by phvalguima** [comment]
Hi team,

We are seeing this same issue now and then.
Indeed it is not easy to reproduce.

There is a race condition where, if ```config-changed``` event runs before the ```istio-pilot``` events, then the gateway never gets rendered. It is because in practice, the ```config-changed``` that creates the istio-gateway.

You can discover this issue by running:
```
$ kubectl get gw -A
<no resources found>
```

Then, the work-around is to run:
```
$ juju run --unit istio-pilot/0 -- "export JUJU_DISPATCH_PATH=hooks/config-changed; ./dispatch"
```

That will render the istio gateway configuration.

The issue is because the gateway is created by:
```
        self.framework.observe(self.on.config_changed, self.handle_default_gateway)

        self.framework.observe(
            self.on[DEFAULT_RELATION_NAME].relation_changed, self.handle_default_gateway
        )
        self.framework.observe(self.on["istio-pilot"].relation_changed, self.send_info) ## <<<-------------
```

Where we never actually use DEFAULT_RELATION_NAME (which is, in the end, ```gateway```, [as you can see here](https://github.com/canonical/istio-operators/blob/78eb1aff1c0a5535c6426dc98430336b15bfe03b/charms/istio-pilot/src/istio_gateway_name_provider.py#L6) ). So, in practice, in Kubeflow deployments, only ```config-changed``` actually triggers the default gateway creation.

Therefore, the solution should look like:
```
        self.framework.observe(self.on.config_changed, self.handle_default_gateway)

        self.framework.observe(
            self.on[DEFAULT_RELATION_NAME].relation_changed, self.handle_default_gateway
        )
        self.framework.observe(self.on["istio-pilot"].relation_changed, self.pilot_relation_changed)

......

    def pilot_relation_changed(event):
        self.handle_default_gateway(event)
        self.send_info(event)
```

That way, the creation of the gateway is guaranteed.
